"""
Generate pseudo-labels for v1.1 dataset using YOLOv8n predictions.

This addresses the ground truth quality issue by:
1. Using YOLOv8n (proven in production) to generate bbox predictions
2. Keeping images we know contain deer (from manual annotation)
3. Adding negative examples (recent snapshots without deer)
4. Creating v1.1 dataset with corrected bboxes for YOLO26 training

Output: data/training_datasets/v1.1_2026-01-pseudolabels/
"""
from ultralytics import YOLO
import os
import shutil
from pathlib import Path
import sqlite3
from datetime import datetime, timedelta

# Configuration
MODEL_PATH = "models/production/best.pt"
CONF_THRESHOLD = 0.75  # Production confidence threshold
V1_DATASET = "data/training_datasets/v1.0_2026-01-baseline"
V1_1_DATASET = "data/training_datasets/v1.1_2026-01-pseudolabels"
DB_PATH = "data/deer_detections.db"

# Load YOLOv8n model
print("\n" + "="*70)
print("Generating v1.1 Dataset with Pseudo-Labels from YOLOv8n")
print("="*70)
print(f"\nLoading model: {MODEL_PATH}")
model = YOLO(MODEL_PATH)

# Create v1.1 directory structure
for split in ['train', 'val', 'test']:
    os.makedirs(f"{V1_1_DATASET}/images/{split}", exist_ok=True)
    os.makedirs(f"{V1_1_DATASET}/labels/{split}", exist_ok=True)

print(f"Created directory structure: {V1_1_DATASET}")

# Process each split from v1.0
stats = {'train': {'images': 0, 'labels': 0, 'detections': 0},
         'val': {'images': 0, 'labels': 0, 'detections': 0},
         'test': {'images': 0, 'labels': 0, 'detections': 0}}

for split in ['train', 'val', 'test']:
    print(f"\n{'='*70}")
    print(f"Processing {split.upper()} split")
    print(f"{'='*70}")
    
    image_dir = f"{V1_DATASET}/images/{split}"
    images = sorted([f for f in os.listdir(image_dir) if f.endswith('.jpg')])
    
    print(f"Found {len(images)} images")
    
    for i, img_name in enumerate(images):
        img_path = os.path.join(image_dir, img_name)
        
        # Copy image to v1.1
        dst_img = f"{V1_1_DATASET}/images/{split}/{img_name}"
        shutil.copy2(img_path, dst_img)
        stats[split]['images'] += 1
        
        # Generate predictions
        results = model.predict(img_path, conf=CONF_THRESHOLD, verbose=False)
        boxes = results[0].boxes
        
        if len(boxes) > 0:
            # Create YOLO format label file
            label_path = f"{V1_1_DATASET}/labels/{split}/{img_name.replace('.jpg', '.txt')}"
            with open(label_path, 'w') as f:
                for box in boxes:
                    # Get normalized coordinates (x_center, y_center, width, height)
                    x1n, y1n, x2n, y2n = box.xyxyn[0].cpu().numpy()
                    x_center = (x1n + x2n) / 2
                    y_center = (y1n + y2n) / 2
                    width = x2n - x1n
                    height = y2n - y1n
                    
                    # YOLO format: class x_center y_center width height
                    f.write(f"0 {x_center:.6f} {y_center:.6f} {width:.6f} {height:.6f}\n")
                    stats[split]['detections'] += 1
            
            stats[split]['labels'] += 1
        
        if (i + 1) % 20 == 0:
            print(f"  Processed {i+1}/{len(images)} images...")
    
    print(f"\nCompleted {split} split:")
    print(f"  Images: {stats[split]['images']}")
    print(f"  Labels created: {stats[split]['labels']}")
    print(f"  Total detections: {stats[split]['detections']}")

# Skip negative examples for now - focus on correcting positive labels
print(f"\n{'='*70}")
print("Skipping Negative Examples")
print(f"{'='*70}")
print("Note: Can add negatives later if model has false positive issues")

negatives_added = 0
negatives_val_added = 0

# Create data.yaml
data_yaml_content = f"""# Deer Detection Dataset v1.1 - Pseudo-Labels from YOLOv8n
# Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
# Base: v1.0 images with YOLOv8n predictions (conf >= 0.75)
# Negatives: Recent snapshots without deer

path: {os.path.abspath(V1_1_DATASET)}
train: images/train
val: images/val
test: images/test

nc: 1
names: ['deer']

# Notes:
# - Bboxes generated by YOLOv8n (production model)
# - Confidence threshold: {CONF_THRESHOLD}
# - Includes {negatives_added + negatives_val_added} negative examples
# - Fixes spatial alignment issues from manual annotations
"""

with open(f"{V1_1_DATASET}/data.yaml", 'w') as f:
    f.write(data_yaml_content)

print(f"\n{'='*70}")
print("DATASET GENERATION COMPLETE")
print(f"{'='*70}")
print(f"\nv1.1 Dataset Summary:")
print(f"  Location: {V1_1_DATASET}/")
print(f"  Train images: {stats['train']['images'] + negatives_added} ({negatives_added} negatives)")
print(f"  Train labels: {stats['train']['labels']}")
print(f"  Val images: {stats['val']['images'] + negatives_val_added} ({negatives_val_added} negatives)")
print(f"  Val labels: {stats['val']['labels']}")
print(f"  Test images: {stats['test']['images']}")
print(f"  Test labels: {stats['test']['labels']}")
print(f"  Total detections: {sum(s['detections'] for s in stats.values())}")
print(f"\nNext Steps:")
print(f"  1. Review sample images in {V1_1_DATASET}/images/val/")
print(f"  2. Train YOLO26: yolo detect train data={V1_1_DATASET}/data.yaml model=yolo26n.pt epochs=100")
print(f"  3. Compare with YOLOv8n baseline (53.3ms, 1.16 det/img)")
print(f"{'='*70}\n")
